version: '3.8'

services:
  redis:
    extends:
      file: docker-compose-base.yml
      service: redis
    networks:
      - hobbybox
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9400:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    networks:
      - hobbybox
  pgsync:
    extends:
      file: docker-compose-base.yml
      service: pgsync
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to OpenSearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - redis
      - opensearch
    environment:
      - ELASTICSEARCH=false
      - OPENSEARCH=true
      - ELASTICSEARCH_HOST=opensearch
    networks:
      - hobbybox
networks:
  hobbybox:
    name: hobbybox-network
    external: true
