version: '3.8'

services:
  redis:
    image: redis
    command: redis-server --requirepass PLEASE_CHANGE_ME
    networks:
    - hobbybox
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    networks:
      - hobbybox
  pgsync:
    image: 454018325523.dkr.ecr.us-east-1.amazonaws.com/pgsync:latest
    container_name: pgsync
    build:
      context: .
      dockerfile: Dockerfile
    command: ./runserver.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to Elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - redis
    environment:
      - PG_USER=hobbybox
      - PG_HOST=db
      - PG_PORT=5432
      - PG_PASSWORD=development
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=PLEASE_CHANGE_ME
      - ELASTICSEARCH=true
      - OPENSEARCH=false
  networks:
    - hobbybox
networks:
  hobbybox:
    external: true